# Assigment 1

## Text to organized data: Annual Reports 
---

The purpose of this assignment is to grasp the fundamentals of working with text in python performing a hands-on data pipeline where the initial input is simply annual reports in pdfs, the idea will be to reproduce into certain extent what is revised in the notebooks 1.1, 1.2 and 1.3 aiming to have workable datasets which will be important building blocks for the final use case.

The following assignment is divided into 3 parts: Mining PDFs, Retrieving files and Text organization where is each part will be asked to create functions or routines for data processing.  

The expected output of this notebook is a clean, organized data in two standard text formats:

1. **Corpus** - a collection of text
2. **Document-Term Matrix** - word counts in matrix format

---
## Part 1: Mining PDFs

1. Intsall the library **`textract`** using pip and import

In [1]:
#!pip install textract

In [2]:
import textract

2. Using the library **`os`** we can access the path of our working directories, here is an example

In [3]:
import os  
opath = os.getcwd()  
print ("The current working directory is %s" % opath)

The current working directory is /Users/pedrohserrano/text-analytics-bootcamp-pggm

Use the *`os.listdir(opath)`* function to show the files contained in that folder

In [4]:
#path = 'AnnualReportsTest/'
path = 'AnnualReports/'

3. Write a function or process that will create a list of names of files of certain folder

In [5]:
file_names = []
# iterate through all file names found in that path
# This option gets all files = !ls AnnualReports
for file in os.listdir(path):
    # append all files names to a list
    if file[0]!='.' and file[-3:]=='pdf': #to handle issue with hidden files and non-pdf files
        file_names.append(file)

In [6]:
file_names

['GEA_Group_(2018).pdf',
 'BTG_(2018).pdf',
 'Idexx_Laboratories_(2018).pdf',
 'Haier_Electronics_Group_(2018).pdf',
 'Newfield_Exploration_(2018).pdf',
 'Automatic_Data_Processing_(2018).pdf',
 'HSBC_Holdings_(2018).pdf',
 'Freightways_(2018).pdf',
 'Pfizer_(2018).pdf',
 'Cinemark_(2018).pdf',
 'Davide_Campari-Milano_(2018).pdf',
 'Kimberly-Clark_de_Mexico_(2018).pdf',
 'Nippon_Shokubai_(2018).pdf',
 'K+S_(2018).pdf',
 'Aboitiz_Power_(2018).pdf',
 'AerCap_Holdings_(2018).pdf',
 'Leonardo_(2018).pdf',
 'Jiangxi_Copper_(2018).pdf',
 'BB_Biotech_(2018).pdf',
 'Canon_(2018).pdf',
 'A_G_Barr_(2018).pdf',
 'Avianca_Holdings_(2018).pdf',
 'Compass_Group_(2018).pdf',
 'New_Gold_(2018).pdf',
 'Cimarex_Energy_(2018).pdf',
 'Helvetia_Holding_(2018).pdf',
 'E_on_(2018).pdf',
 'Eircom_GROUP_(2018).pdf',
 'BHP_Group_(UK)_(2018).pdf',
 'Glow_Energy_(2018).pdf',
 'City_Of_London_Investment_Group_(2018).pdf',
 'Costco_Wholesale_(2018).pdf',
 'Fresenius_Medical_Care_(2018).pdf',
 'Elders_(2018).pdf',
 'Guotai_Junan_International_Holdings_(2018).pdf',
 'Cardno_(2018).pdf',
 'BASF_(2018).pdf',
 'Hisamitsu_Pharmaceutical_(2018).pdf',
 'Corbion_(2018).pdf',
 'Marriott_International_(2018).pdf',
 'Liquefied_Natural_Gas_Limited_(2018).pdf',
 'Bid_Corporation_(2018).pdf',
 'GW_Pharmaceuticals_(2018).pdf',
 'Austal_(2018).pdf',
 'Reach_(2018).pdf',
 'Ainsworth_Game_Technology_(2018).pdf',
 'News_Corp_(2018).pdf',
 'Kose_(2018).pdf',
 'Chunghwa_Telecom_(2018).pdf',
 'Gran_Tierra_Energy_(2018).pdf',
 'Karoon_Gas_Australia_(2018).pdf',
 'Provident_Financial_(2018).pdf',
 'Holmen_(2018).pdf',
 'McDermott_International_(2018).pdf',
 'IG_Group_Holdings_(2018).pdf',
 'GATX_(2018).pdf',
 'BCE_(2018).pdf',
 'Freenet_(2018).pdf',
 'Masisa_(2018).pdf',
 'Comcast_(2018).pdf',
 'Koito_Manufacturing_(2018).pdf',
 'Fairfax_Financial_Holdings_(2018).pdf',
 'BE_Semiconductor_Industries_(2018).pdf',
 'Greencore_Group_(2018).pdf',
 'Prudential_(2018).pdf',
 'Genting_(2018).pdf',
 'Qube_Holdings_(2018).pdf',
 'Huntington_Ingalls_Industries_(2018).pdf',
 'Nabtesco_(2018).pdf',
 'Ping_An_Insurance_(2018).pdf',
 'Indivior_(2018).pdf',
 'Echo_Global_Logistic_(2018).pdf',
 'CTT_Correios_de_Portugal_(2018).pdf',
 'Life_Healthcare_Group_Holdings_(2018).pdf',
 'Capita_Group_(2018).pdf',
 'Keppel_Corporation_(2018).pdf',
 'Joy_Global_(2018).pdf',
 'Acom_(2018).pdf',
 'Jardine_Strategic_Holdings_(2018).pdf',
 'DSM_(2018).pdf',
 'Fomento_de_Construcciones_y_Contratas_(2018).pdf',
 'Kingfisher_(2018).pdf']

4. Write a function that will iterate each of the names of the previous list, extract the text and write to txt format.

In [7]:
def write_pdf():
    extracted_pdfs = []
    for file_name in file_names: 
        try:
            text = str(textract.process(path+file_name))
            file = open(path+file_name+'.txt','w+')
            file.write(text)
        except Exception:
            continue

In [8]:
import time
start_time = time.time()
#write_pdf()
print("--- %s seconds ---" % (time.time() - start_time))

--- 16492.803255081177 seconds ---

---
## Part 2: Retrieving files

Another way of retrieve the filenames of certain format is with via terminal `!ls path*.txt`
1. Create a list with the name of the reports saved in txt  
The list should look like this:

In [5]:
#annual_report_files = !ls AnnualReportsTest/*.txt
annual_report_files = !ls AnnualReports/*.txt

In [6]:
annual_report_files = [c[14:-4] for c in annual_report_files]

2. Create a function or process that will load all the existing reports in `txt` format and save it in a dictionary

In [7]:
# Load pickled files
data = {}
for i, c in enumerate(annual_report_files):
    with open(path+c+'.txt', "r") as file:
        data[c] = file.read()

In [8]:
len(data.keys())

92

In [9]:
print(data['ABN_AMRO_Group_(2018).pdf'][:1000])

b"ABN AMRO Bank N.V.ABN AMRO Group N.V. Annual Report 2018\x0c   \n\nTable of contents\n\n2Introduction\n\nAbout this report \nKey figures and profile \nABN AMRO shares \n\n2\n3\n4\n\n5Strategy and \n\nperformance\n6\nEconomic environment \n8\nRegulatory environment \n10\nStrategy \n13\nGroup performance \nBusiness performance \n20\nResponsibility statement  34\n\n35Risk, funding & \n\ncapital\nIntroduction to Risk, \nfunding &\xc2\xa0capital \n\nRisk, funding & \n\n123Leadership & \n\ngovernance\nIntroduction to Leadership \n\n36\n\n& governance \n\nExecutive Board and \n\ncapital\xc2\xa0management \n\n37\n\nExecutive\xc2\xa0Committee \n\nRisk, funding & \ncapital\xc2\xa0review \n\nSupervisory Board \nReport of the \n\n65\n\nAdditional risk, funding \n\n&\xc2\xa0capital\xc2\xa0disclosures  116\n\nSupervisory\xc2\xa0Board \nGeneral Meeting and \n\nshareholder\xc2\xa0structure \nCodes and regulations \nLegal structure \nRemuneration report \n\n124\n\n124\n128\n\n132\n\n138\n141\n144\n14

---
## Part 3: Text organization

1. Import `pandas` and perform the tasks of data cleaning revised in the `Text Processing` notebook in order to get a Corpus and a Document-term Matrix, add or remove cleaning functions if necessary

In [10]:
import pandas as pd

In [11]:
data.keys()

dict_keys(['ABN_AMRO_Group_(2018).pdf', 'AGNC_Investment_(2018).pdf', 'A_G_Barr_(2018).pdf', 'Aboitiz_Power_(2018).pdf', 'Acer_(2018).pdf', 'Acom_(2018).pdf', 'AerCap_Holdings_(2018).pdf', 'Ainsworth_Game_Technology_(2018).pdf', 'Austal_(2018).pdf', 'Autohome_(2018).pdf', 'Automatic_Data_Processing_(2018).pdf', 'Avianca_Holdings_(2018).pdf', 'BAIC_Motor_Corporation_(2018).pdf', 'BASF_(2018).pdf', 'BCE_(2018).pdf', 'BE_Semiconductor_Industries_(2018).pdf', 'BHP_Group_(UK)_(2018).pdf', 'Bid_Corporation_(2018).pdf', 'CTT_Correios_de_Portugal_(2018).pdf', 'Canon_(2018).pdf', 'Capita_Group_(2018).pdf', 'Cardno_(2018).pdf', 'Carlsberg_(2018).pdf', 'Chunghwa_Telecom_(2018).pdf', 'Cimarex_Energy_(2018).pdf', 'Cinemark_(2018).pdf', 'City_Of_London_Investment_Group_(2018).pdf', 'Close_Brothers_Group_(2018).pdf', 'Comcast_(2018).pdf', 'Compass_Group_(2018).pdf', 'Corbion_(2018).pdf', 'Costco_Wholesale_(2018).pdf', 'DSM_(2018).pdf', 'Davide_Campari-Milano_(2018).pdf', 'Deutsche_Bank_(2018).pdf', 'E_on_(2018).pdf', 'Echo_Global_Logistic_(2018).pdf', 'Edison_International_(2018).pdf', 'Eircom_GROUP_(2018).pdf', 'Elders_(2018).pdf', 'Fairfax_Financial_Holdings_(2018).pdf', 'Fomento_de_Construcciones_y_Contratas_(2018).pdf', 'Freightways_(2018).pdf', 'GATX_(2018).pdf', 'GW_Pharmaceuticals_(2018).pdf', 'Genting_(2018).pdf', 'Genworth_Mortgage_Insurance_Australia_(2018).pdf', 'Glow_Energy_(2018).pdf', 'Gran_Tierra_Energy_(2018).pdf', 'Greencore_Group_(2018).pdf', 'Guotai_Junan_International_Holdings_(2018).pdf', 'HCP_(2018).pdf', 'HSBC_Holdings_(2018).pdf', 'Haier_Electronics_Group_(2018).pdf', 'Helvetia_Holding_(2018).pdf', 'Hisamitsu_Pharmaceutical_(2018).pdf', 'Holmen_(2018).pdf', 'Huntington_Ingalls_Industries_(2018).pdf', 'IG_Group_Holdings_(2018).pdf', 'Idexx_Laboratories_(2018).pdf', 'Indivior_(2018).pdf', 'Japan_Post_Bank_(2018).pdf', 'Jardine_Strategic_Holdings_(2018).pdf', 'Jiangxi_Copper_(2018).pdf', 'K+S_(2018).pdf', 'Karoon_Gas_Australia_(2018).pdf', 'Keppel_Corporation_(2018).pdf', 'Kimberly-Clark_de_Mexico_(2018).pdf', 'Kingfisher_(2018).pdf', 'Koito_Manufacturing_(2018).pdf', 'Kose_(2018).pdf', 'Life_Healthcare_Group_Holdings_(2018).pdf', 'Liquefied_Natural_Gas_Limited_(2018).pdf', 'Lynas_(2018).pdf', 'Marriott_International_(2018).pdf', "Marston's_(2018).pdf", 'Masisa_(2018).pdf', 'McDermott_International_(2018).pdf', 'Mitsubishi_Materials_Corporation_(2018).pdf', 'Modern_Times_Group_(2018).pdf', 'Nabtesco_(2018).pdf', 'New_Gold_(2018).pdf', 'Newfield_Exploration_(2018).pdf', 'News_Corp_(2018).pdf', 'Nippon_Shokubai_(2018).pdf', 'Pfizer_(2018).pdf', 'Ping_An_Insurance_(2018).pdf', 'Promotora_y_Operadora_de_Infraestructura_(2018).pdf', 'Provident_Financial_(2018).pdf', 'Prudential_(2018).pdf', 'Qube_Holdings_(2018).pdf', 'Reach_(2018).pdf'])

In [12]:
data_formatted = {key: [value] for (key, value) in data.items()}
pd.set_option('max_colwidth',1000)
data_df = pd.DataFrame.from_dict(data_formatted).transpose()
data_df.columns = ['report']
data_df = data_df.sort_index()
data_df.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             report
ABN_AMRO_Group_(2018).pdf   b"ABN AMRO Bank N.V.ABN AMRO Group N.V. Annual Report 2018\x0c   \n\nTable of contents\n\n2Introduction\n\nAbout this report \nKey figures and profile \nABN AMRO shares \n\n2\n3\n4\n\n5Strategy and \n\nperformance\n6\nEconomic environment \n8\nRegulatory environment \n10\nStrategy \n13\nGroup performance \nBusiness performance \n20\nResponsibility statement  34\n\n35Risk, funding & \n\ncapital\nIntroduction to Risk, \nfunding &\xc2\xa0capital \n\nRisk, funding & \n\n123Leadership & \n\ngovernance\nIntroduction to Leadership \n\n36\n\n& governance \n\nExecutive Board and \n\ncapital\xc2\xa0management \n\n37\n\nExecutive\xc2\xa0Committee \n\nRisk, funding & \ncapital\xc2\xa0review \n\nSupervisory Board \nReport of the \n\n65\n\nAdditional risk, funding \n\n&\xc2\xa0capital\xc2\xa0disclosures  116\n\nSupervisory\xc2\xa0Board \nGeneral Meeting and \n\nshareholder\xc2\xa0structure \nCodes and regulations \nLegal structure \nRemuneration report \n\n124\n\n124\n128\n\n132\n\n138\n141\n144...
AGNC_Investment_(2018).pdf  b'Providing Private Capital to the U.S. Housing Market Through\n\nINVESTMENT EXCELLENCE\n\n2018 ANNUAL REPORT\n\n\x0c\x0cDEAR FELLOW STOCKHOLDERS:\n\n2018 marked a signi\xef\xac\x81cant milestone for AGNC Investment Corp.\xe2\x80\x94our tenth anniversary as a public\ncompany, which we celebrated by ringing the Nasdaq opening bell on May 15, 2018.\n\nPictured (left to right) AGNC\xe2\x80\x99s board of directors as of May 15, 2018: Paul Mullings, Larry Harvey, Gary Kain (Chief Executive\nO\xef\xac\x83cer and Chief Investment O\xef\xac\x83cer), Prue Larocca (Chair), Morris Davis. Not Pictured: Donna Blank, who became a\ndirector on December 3, 2018.\n\nWhile we remain steadfasff\nour stockholders, this\nsigni\xef\xac\x81cant accomplishment provides an opportunity to re\xef\xac\x82ect upon AGNC\xe2\x80\x99s achievements over the past decade:\n\nsed on generating attractive long-term returns forff\n\ntly focuff\n\n\xe2\x80\xa2 Industry-leading total stock and economic returns;\n\n\xe2\x...
A_G_Barr_(2018).pdf         b'A.G. BARR p.l.c. \nAnnual Report \nand Accounts \nJanuary 2018\n\n\x0cIRN-BRU\nInnovation and \nreformulation success\n\nThe IRN-BRU brand is going from strength  \nto strength \xe2\x80\x93 big on taste but with no sugar,  \nIRN-BRU XTRA sold the equivalent of more than \n60 million cans across the UK in 2017, while the \nOriginal & Best regular IRN-BRU, still made with the \nsame secret recipe essence, now contains half the  \nsugar and tastes great.\n\nRead more from page 14 \n\n\x0c8.0%IRN-BRU TOTAL \n\nBRAND SALES GROWTH\n\n\x0cBuilding the  \nRubicon brand\n\nBuilding on its 30-year heritage our Rubicon brand \nis broadening its reach \xe2\x80\x93 whether through our \ninnovative new no added sugar Rubicon Spring \nrange, or our new sponsorship as official soft drink \nof the English Cricket Team, we\xe2\x80\x99re growing the \nbrand and introducing new consumers  \nto our delicious Rubicon drinks.\n\nRead more on pages 15 and 19 \n\n\x0c5.3%RUBICON BRAND \n\nSALES GROWTH\n\...
Aboitiz_Power_(2018).pdf    b'Scanned with CamScanner\n\n\x0c\x0cCOVER SHEET \n\n \n  \n \n  \n\n \n  \n \n  \n\n \n \n  \n  \n \n \n  \n  \n( Company\'s Full Name ) \n \n \n \n \n,  B  O  N \nI \n \n \n \n \nT  Y \n   C \n \n \n \n \n  \n  \n  \n  \n\n \nI \n \n  \n\n \n  \n\n \n\n \n\n \n \n\n \n \nA\n \n \n  \n \n  \n\n \n \n\n \n \n\n \n \n\n \n \nB  O \n \n  \n \n  \n\n \n  \n \n  \n\n \n \n\n \n \nI \n \n  \n \n  \n\n \n \n\n \n \nT \n \n  \n \n  \n\n \n \n\nI \n\n  \n\n  \n\n \n \n\n \n\n \n\n \n \n \n \nZ \n \n  \n \n  \n\n \n \n\n \n \n\n \n\n \n  \n \n  \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n \n \nP  O  W  E  R \n \n \n  \n  \n \n \n  \n  \n\n \n  \n \n  \n\n \n  \n \n  \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n \n\n \n3\n  \n \n\n \n4\n \nS.E.C. Registration Number \n \n\n \n \nC  1  9  9  8  0  0  1\n \n \n \n \n \n \n  \n \n  \n\n \n \n \nC  O  R  P  O  R  A  T \n \n \n  \n  \n \n \n  \n  \n\n \n \nI  O  N \n \n \n  \n ...
Acer_(2018).pdf             b'ACER INCORPORTED\n2018 ANNUAL REPORT\n\nPublication Date : April 16, 2019\n\n\x0cAPPENDIX\n\n1. Name, Title and Contact Details of Company\'s Spokespersons:\n\nPrincipal \n\nMeggy Chen\n\nCFO\n\n+886-2-2696-1234\n\nMeggy.Chen@acer.com\n\nDeputy\n\nWayne Chang\n\nManager\n\n+886-2-2719-5000\n\nWayne.Chang@acer.com\n\n2. Address and Telephone Numbers of Company\'s Headquarter and Branches\n\nOffice\n\nAddress\n\nTel\n\nAcer Inc.\nRegistered Address\n\n7F.-5, No.369, Fuxing N. Rd., Songshan Dist., \nTaipei City 105, Taiwan  \n\n+886-2-2719-5000\n\nAcer Inc.\n(Xizhi Office)\n\nAcer Inc.\n(Hsinchu Branch)\n\nAcer Inc.\n(Taichung Branch)\n\n8F., No.88, Sec. 1, Xintai 5th Rd., Xizhi Dist., New \nTaipei City 221, Taiwan \n\n+886-2-2696-1234\n\n3F., No.139, Minzu Rd., East Dist., Hsinchu City \n300, Taiwan\n\n+886-3-534-9490\n\n3F., No.371, Sec. 1, Wenxin Rd., Nantun Dist., \nTaichung City 408, Taiwan\n\n+886-4-2250-3355\n\nAcer Inc.\n(Kaohsiung Branch)\n\n4F.-6, No.38, Xinguang Rd., Ling...

In [13]:
import re
import string

In [14]:
def clean_text(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('<.*?>', ' ', text)
    text = re.sub('\\n', ' ', text) 
    text = re.sub('\n', ' ', text) 
    text = re.sub('\t', ' ', text) 
    return text

In [15]:
data_clean = pd.DataFrame(data_df.report.apply(clean_text))

In [16]:
data_clean['company_name'] = [c[:-11] for c in data_clean.index]

**This is the Corpus**

In [17]:
data_clean.head()

,report,company_name
ABN_AMRO_Group_(2018).pdf,babn amro bank nvabn amro group nv annual report nntable of this report nkey figures and profile nabn amro shares and environment environment performance nbusiness performance statement funding nncapitalnintroduction to risk nfunding nnrisk funding nngovernancenintroduction to leadership governance nnexecutive board and nnrisk funding nnsupervisory board nreport of the risk funding ngeneral meeting and ncodes and regulations nlegal structure nremuneration report financial statements income statement nconsolidated statement income nconsolidated statement nconsolidated statement nconsolidated statement nnotes to the consolidated ncompany financial statements nother information statements amro group annual report and performancerisk funding capitalleadershipgovernanceannual financial statementsotherintroductionstrategy and performancerisk funding capitalleadership governanceannual financial about this this reportnnthis is the annual re...,ABN_AMRO_Group
AGNC_Investment_(2018).pdf,bproviding private capital to the us housing market throughnninvestment annual fellow marked a milestone for agnc investment tenth anniversary as a publicncompany which we celebrated by ringing the nasdaq opening bell on may left to right board of directors as of may paul mullings larry harvey gary kain chief and chief investment prue larocca chair morris davis not pictured donna blank who became andirector on december we remain steadfasffnour stockholders accomplishment provides an opportunity to upon achievements over the past decadennsed on generating attractive longterm returns forffnntly industryleading total stock and economic dividends paid to internalization of management remarkable growth in equity capital successful navigation of challenging macroeconomic events economic cycles and interest rate environmentsnna g n c a n n u a l r e p o r total stock and economic returnsnsince inception our primary objective has been to provide our stockholder...,AGNC_Investment
A_G_Barr_(2018).pdf,bag barr plc nannual report nand accounts njanuary and nreformulation successnnthe irnbru brand is going from strength nto strength big on taste but with no sugar nirnbru xtra sold the equivalent of more than million cans across the uk in while the noriginal best regular irnbru still made with the nsame secret recipe essence now contains half the nsugar and tastes greatnnread more from page total nnbrand sales the nrubicon brandnnbuilding on its heritage our rubicon brand nis broadening its reach whether through our ninnovative new no added sugar rubicon spring nrange or our new sponsorship as official soft drink nof the english cricket team growing the nbrand and introducing new consumers nto our delicious rubicon drinksnnread more on pages and brand nnsales benedetto nnew partnershipnnwe recognise the advantages that working in npartnership can deliver our new longterm nagreement with leading soft drinks producer nsan benedetto gives us the exclusive uk and ...,A_G_Barr
Aboitiz_Power_(2018).pdf,bscanned with sheet nn n n n nn n n n nn n n n n n n n n companys full name n n n n n b o n ni n n n n nt y n c n n n n n n n n nn ni n n nn n nn nn nn n nn n nan n n n n nn n nn n nn n nn n nb o n n n n nn n n n nn n nn n ni n n n n nn n nn n nt n n n n nn n nni nn nn nn n nn nn nn n n n nz n n n n nn n nn n nn nn n n n nn n nn n nn n nn n nn n nn n nn n nn n nn n n n np o w e r n n n n n n n n nn n n n nn n n n nn nn nn nn nn nn nn n nn n nn n nn n nn n nn n nn n nn n nn nsec registration number n nn n nc n n n n n n n n nn n n nc o r p o r a t n n n n n n n n nn n ni o n n n n n n n n n nn n n n nn n n n nn n n n nn n n n nn n n n nn n n n nn n n n n nn nn nn nn nn nn nn n nn nn nn n n n nn nn nn n n d n n n n nt y ni nc n n n n np h ni nl nn nn nn nn nn nn nn nn n n n n n ni p p nn n ns t r e e t n n n n ni g nt a g u n n n n n n ni n e s n nbusiness ad...,Aboitiz_Power
Acer_(2018).pdf,bacer annual reportnnpublication date april name title and contact details of companys spokespersonsnnprincipal nnmeggy address and telephone numbers of companys headquarter and branchesnnofficennaddressnntelnnacer incnregistered fuxing n rd songshan dist ntaipei city taiwan incnxizhi officennacer incnhsinchu branchnnacer incntaichung sec xintai rd xizhi dist new ntaipei city taiwan minzu rd east dist hsinchu city sec wenxin rd nantun dist ntaichung city incnkaohsiung xinguang rd lingya dist nkaohsiung city incnshipping warehouse nmanagement center neixin rd luzhu dist taoyuan city address and contact details of acer shareholders servicesnnaddress fuxing n rd songshan dist taipei city taiwan ntel nemail address and contact details of auditing cpas in the most recent yearnnhueichen chang and tzuchieh tang at kpmgnnname naddress sec xinyi rd xinyi dist taipei city taiwan ntel overseas securities exchangennlisted market for gdrs london stoc...,Acer

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')

In [19]:
data_cv = cv.fit_transform(data_clean.report)
data_tokens = cv.get_feature_names()

In [20]:
data_matrix = pd.DataFrame(data_cv.toarray(), columns=data_tokens)
data_matrix.index = data_clean.index

**This is the Matrix**

In [21]:
data_matrix.head()

,aa,aaa,aaaa,aaaaaa,aaanaaa,aaannf,aabouche,aabouchenchief,aac,aace,...,zwanzigste,zweite,zweiundzwanzigste,zwi,zwijndrecht,zygos,zylum,zyrus,zzzquil,zzzs
ABN_AMRO_Group_(2018).pdf,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGNC_Investment_(2018).pdf,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A_G_Barr_(2018).pdf,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Aboitiz_Power_(2018).pdf,4,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Acer_(2018).pdf,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

---
## Part 4: Financial stop words

Note: The matrix and the corpus should be available in order to perform this step

1. Write a process or function that will retrieve the top 30 used words per document and save it in the format of your preference

In [22]:
import pandas as pd

In [23]:
#data = pd.read_pickle('pickle/AnnualReports_matrix.pkl')
data = data_matrix.transpose()
data.head()

,ABN_AMRO_Group_(2018).pdf,AGNC_Investment_(2018).pdf,A_G_Barr_(2018).pdf,Aboitiz_Power_(2018).pdf,Acer_(2018).pdf,Acom_(2018).pdf,AerCap_Holdings_(2018).pdf,Ainsworth_Game_Technology_(2018).pdf,Austal_(2018).pdf,Autohome_(2018).pdf,...,Newfield_Exploration_(2018).pdf,News_Corp_(2018).pdf,Nippon_Shokubai_(2018).pdf,Pfizer_(2018).pdf,Ping_An_Insurance_(2018).pdf,Promotora_y_Operadora_de_Infraestructura_(2018).pdf,Provident_Financial_(2018).pdf,Prudential_(2018).pdf,Qube_Holdings_(2018).pdf,Reach_(2018).pdf
aa,0,0,0,4,1,0,0,1,0,0,...,0,0,0,1,3,0,0,11,0,0
aaa,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,2,2,0,9,0,0
aaaa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaaaaa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaanaaa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

<br>
Find the top 30 words per report

In [24]:
top_dict = {}
for c in data.columns:
    top = data[c].sort_values(ascending=False).head(30)
    top_dict[c]= list(zip(top.index, top.values))

In [25]:
pd.DataFrame.from_dict(top_dict)

,ABN_AMRO_Group_(2018).pdf,AGNC_Investment_(2018).pdf,A_G_Barr_(2018).pdf,Aboitiz_Power_(2018).pdf,Acer_(2018).pdf,Acom_(2018).pdf,AerCap_Holdings_(2018).pdf,Ainsworth_Game_Technology_(2018).pdf,Austal_(2018).pdf,Autohome_(2018).pdf,...,Newfield_Exploration_(2018).pdf,News_Corp_(2018).pdf,Nippon_Shokubai_(2018).pdf,Pfizer_(2018).pdf,Ping_An_Insurance_(2018).pdf,Promotora_y_Operadora_de_Infraestructura_(2018).pdf,Provident_Financial_(2018).pdf,Prudential_(2018).pdf,Qube_Holdings_(2018).pdf,Reach_(2018).pdf
0,"(financial, 1235)","(securities, 435)","(year, 346)","(nn, 1419)","(financial, 783)","(nn, 1068)","(financial, 364)","(financial, 259)","(nn, 1085)","(nn, 1199)",...,"(nn, 1060)","(million, 825)","(march, 90)","(pfizer, 182)","(nn, 1450)","(nn, 1146)","(loans, 948)","(million, 480)","(report, 162)","(million, 514)"
1,"(risk, 912)","(income, 335)","(january, 340)","(power, 455)","(company, 773)","(year, 438)","(group, 254)","(group, 225)","(financial, 251)","(business, 461)",...,"(year, 145)","(company, 698)","(consolidated, 75)","(health, 145)","(financial, 1043)","(toll, 949)","(loan, 667)","(financial, 430)","(financial, 105)","(group, 462)"
2,"(funding, 857)","(value, 303)","(report, 308)","(nthe, 389)","(nn, 721)","(business, 386)","(risk, 224)","(nn, 210)","(nnthe, 201)","(prc, 415)",...,"(financial, 139)","(fiscal, 638)","(business, 75)","(patients, 114)","(group, 953)","(road, 671)","(financial, 593)","(liabilities, 388)","(nthe, 74)","(financial, 350)"
3,"(group, 557)","(rate, 244)","(company, 271)","(board, 295)","(assets, 524)","(fiscal, 372)","(value, 216)","(year, 196)","(tax, 187)","(company, 408)",...,"(group, 115)","(june, 526)","(shokubai, 72)","(culture, 82)","(company, 943)","(concession, 661)","(june, 579)","(group, 386)","(annual, 63)","(report, 307)"
4,"(value, 498)","(investment, 211)","(financial, 252)","(aboitiz, 275)","(value, 495)","(company, 353)","(aed, 207)","(report, 176)","(limited, 178)","(tax, 395)",...,"(assets, 103)","(financial, 371)","(year, 68)","(annual, 80)","(insurance, 909)","(concessions, 314)","(bank, 552)","(value, 383)","(audit, 56)","(nthe, 300)"
5,"(december, 430)","(stock, 199)","(group, 235)","(company, 241)","(fair, 395)","(yen, 349)","(investment, 190)","(june, 156)","(report, 164)","(services, 379)",...,"(nthe, 90)","(tax, 368)","(sales, 66)","(global, 75)","(management, 694)","(shares, 273)","(million, 526)","(investment, 324)","(statements, 51)","(december, 249)"
6,"(performancerisk, 426)","(net, 190)","(remuneration, 227)","(energy, 216)","(loss, 365)","(march, 291)","(capital, 188)","(nthe, 148)","(austal, 162)","(information, 369)",...,"(company, 88)","(news, 334)","(based, 65)","(nand, 75)","(risk, 616)","(government, 267)","(fiscal, 450)","(prudential, 316)","(mining, 50)","(year, 248)"
7,"(capital, 391)","(fair, 188)","(barr, 216)","(information, 211)","(income, 333)","(loans, 221)","(waha, 187)","(performance, 120)","(group, 155)","(shares, 357)",...,"(value, 76)","(ended, 318)","(company, 64)","(businessour, 72)","(assets, 517)","(nnthe, 248)","(nn, 326)","(note, 274)","(year, 48)","(company, 238)"
8,"(annual, 390)","(common, 174)","(committee, 204)","(plant, 199)","(recognized, 330)","(financial, 200)","(nthe, 170)","(game, 110)","(year, 130)","(financial, 327)",...,"(june, 74)","(value, 297)","(loss, 63)","(new, 68)","(ping, 485)","(trust, 245)","(value, 294)","(assets, 271)","(nand, 47)","(annual, 234)"
9,"(board, 385)","(financial, 167)","(accounts, 195)","(erc, 184)","(related, 308)","(assets, 192)","(assets, 168)","(ended, 103)","(performance, 128)","(shall, 303)",...,"(nnthe, 72)","(year, 278)","(assets, 59)","(access, 64)","(value, 464)","(december, 238)","(corporation, 291)","(business, 257)","(lithium, 45)","(board, 233)"
10,"(credit, 379)","(assets, 164)","(directors, 181)","(report, 181)","(measured, 305)","(years, 149)","(management, 158)","(value, 96)","(nthe, 117)","(autohome, 297)",...,"(shares, 70)","(services, 273)","(million, 54)","(care, 63)","(december, 461)","(state, 234)","(income, 268)","(tax, 246)","(altura, 44)","(committee, 199)"
11,"(assets, 349)","(december, 154)","(shares, 180)","(bn, 180)","(incorporated, 297)","(operating, 149)","(fair, 137)","(date, 94)","(remuneration, 105)","(income, 296)",...,"(cash, 69)","(assets, 243)","(cash, 51)","(performancefrom, 60)","(china, 456)","(million, 226)","(investment, 264)","(december, 243)","(nn, 41)","(revenue, 185)"
12,"(report, 335)","(mortgage, 148)","(value, 163)","(aboitizpower, 179)","(acer, 278)","(credit, 148)","(nand, 136)","(rights, 89)","(assets, 100)","(million, 285)",...,"(liabilities, 68)","(cash, 216)","(income, 50)","(cancer, 60)","(investment, 435)","(roads, 223)","(held, 263)","(insurance, 242)","(company, 36)","(cash, 180)"
13,"(fair, 324)","(market, 145)","(audit, 160)","(committee, 172)","(profit, 244)","(loan, 139)","(loss, 132)","(tax, 88)","(recognised, 98)","(ordinary, 264)",...,"(exploration, 66)","(net, 212)","(yen, 45)","(leadershipour, 60)","(year, 377)","(nthe, 214)","(assets, 245)","(investments, 241)","(nof, 36)","(assets, 174)"
14,"(nthe, 318)","(risk, 140)","(nthe, 143)","(distribution, 172)","(group, 230)","(nnmillions, 134)","(equity, 120)","(ainsworth, 88)","(value, 97)","(advertising, 261)",...,"(date, 64)","(income, 204)","(net, 44)","(help, 57)","(report, 373)","(federal, 213)","(tax, 225)","(ifrs, 239)","(project, 34)","(share, 172)"
15,"(bank, 318)","(rates, 139)","(board, 134)","(statement, 171)","(business, 218)","(nnas, 129)","(cash, 119)","(share, 84)","(cash, 95)","(december, 246)",...,"(entity, 63)","(operations, 204)","(plant, 42)","(nthe, 54)","(business, 357)","(ps, 200)","(losses, 216)","(report, 234)","(key, 31)","(risk, 167)"
16,"(amro, 317)","(agency, 127)","(share, 132)","(mw, 163)","(comprehensive, 208)","(consolidated, 129)","(company, 119)","(thousand, 84)","(june, 91)","(china, 217)",...,"(tax, 62)","(fair, 199)","(securities, 42)","(medicines, 53)","(profit, 333)","(company, 200)","(net, 215)","(uk, 218)","(nin, 30)","(value, 166)"
17,"(loans, 311)","(repurchase, 125)","(tax, 131)","(corporation, 162)","(consolidated, 199)","(nntotal, 125)","(profit, 115)","(gaming, 83)","(nnaustal, 90)","(share, 216)",...,"(loss, 61)","(foxtel, 193)","(value, 40)","(disease, 52)","(fair, 326)","(mexican, 198)","(sale, 214)","(cent, 215)","(information, 28)","(pension, 165)"
18,"(income, 293)","(agreements, 118)","(cash, 130)","(form, 156)","(cash, 198)","(loss, 123)","(asset, 114)","(cash, 83)","(income, 89)","(agreement, 211)",...,"(recognised, 61)","(including, 192)","(responsible, 40)","(purposeour, 48)","(nthe, 324)","(capital, 194)","(rate, 210)","(plc, 213)","(ore, 26)","(audit, 161)"
19,"(capitalleadership, 292)","(loss, 117)","(ended, 128)","(corporate, 152)","(december, 196)","(million, 119)","(recognised, 112)","(assets, 83)","(information, 85)","(internet, 207)",...,"(fair, 56)","(related, 191)","(financial, 38)","(business, 47)","(rmb, 288)","(rights, 192)","(real, 206)","(profit, 208)","(note, 25)","(plc, 158)"
20,"(nand, 262)","(year, 114)","(business, 120)","(december, 150)","(annual, 195)","(nnthe, 112)","(consolidated, 112)","(revenue, 81)","(annual, 81)","(foreign, 205)",...,"(project, 54)","(information, 188)","(corporate, 37)","(financial, 45)","(asset, 278)","(construction, 177)","(fair, 204)","(income, 204)","(june, 25)","(shares, 154)"
21,"(statementsotherintroductionstrategy, 251)","(reit, 113)","(scheme, 114)","(nnannual, 146)","(nnn, 192)","(audit, 111)","(thousand, 111)","(key, 79)","(profit, 76)","(cash, 203)",...,"(report, 51)","(primarily, 186)","(care, 36)","(development, 45)","(nand, 257)","(nnga, 172)","(estate, 195)","(net, 196)","(directors, 25)","(performance, 152)"
22,"(executive, 245)","(derivative, 111)","(performance, 113)","(management, 136)","(shares, 182)","(current, 110)","(nof, 109)","(company, 78)","(share, 75)","(group, 202)",...,"(reporting, 50)","(revenues, 185)","(tax, 36)","(year, 43)","(income, 233)","(operation, 166)","(capital, 193)","(fair, 195)","(million, 22)","(acquisition, 150)"
23,"(advances, 234)","(tba, 107)","(benefit, 112)","(year, 132)","(new, 176)","(april, 107)","(nin, 94)","(remuneration, 78)","(date, 74)","(including, 198)",...,"(accounting, 50)","(new, 182)","(stock, 36)","(patient, 41)","(capital, 231)","(terms, 165)","(mortgage, 188)","(securities, 194)","(consolidated, 22)","(period, 147)"
24,"(held, 223)","(equity, 102)","(nand, 104)","(group, 125)","(management, 172)","(nncurrent, 106)","(credit, 93)","(recognised, 75)","(million, 73)","(class, 194)",...,"(share, 47)","(consolidated, 175)","(subsidiaries, 36)","(people, 40)","(credit, 211)","(total, 163)","(average, 183)","(nthe, 189)","(cash, 21)","(directors, 146)"
25,"(business, 218)","(cash, 102)","(risk, 104)","(directors, 124)","(risk, 167)","(securities, 102)","(joint, 93)","(nand, 73)","(asset, 72)","(form, 187)",...,"(management, 47)","(stock, 174)","(accounting, 35)","(manufacturing, 40)","(services, 196)","(sa, 162)","(stock, 177)","(policyholder, 181)","(facility, 20)","(statements, 133)"
26,"(management, 213)","(changes, 98)","(pension, 103)","(electricity, 123)","(liabilities, 166)","(payable, 100)","(income, 93)","(audit, 70)","(loss, 70)","(law, 184)",...,"(ended, 46)","(group, 171)","(ended, 34)","(treatment, 40)","(nof, 195)","(financial, 155)","(consolidated, 171)","(withprofits, 180)","(nto, 20)","(date, 132)"
27,"(statements, 210)","(tax, 97)","(executive, 100)","(business, 121)","(net, 165)","(accounts, 100)","(investments, 89)","(market, 67)","(fair, 68)","(subject, 183)",...,"(income, 45)","(digital, 170)","(gain, 32)","(including, 39)","(life, 194)","(agreement, 146)","(allowance, 171)","(equity, 177)","(stage, 20)","(consolidated, 130)"
28,"(liabilities, 207)","(credit, 95)","(management, 100)","(non, 120)","(directors, 159)","(nnprior, 98)","(statements, 83)","(based, 67)","(rights, 68)","(equity, 179)",...,"(risk, 44)","(rate, 164)","(discussion, 32)","(nto, 37)","(shares, 192)","(mexico, 145)","(statements, 159)","(company, 167)","(ended, 19)","(nand, 130)"
29,"(supervisory, 206)","(average, 94)","(annual, 96)","(director, 115)","(note, 155)","(management, 98)","(million, 78)","(profit, 66)","(statements, 67)","(expenses, 177)",...,"(acquisition, 43)","(years, 163)","(retirement, 32)","(world, 36)","(million, 190)","(stock, 140)","(securities, 158)","(based, 164)","(rights, 19)","(management, 130)"

In [26]:
# Let's first pull out the top 30 words for each company
words = []
for company in data.columns:
    top = [word for (word, count) in top_dict[company]]
    for t in top:
        words.append(t)

<br>
The main idea here is to filter or exclude such words from the financial jargon, wich are highly present on each document and presumibly do not represent any insigh, those could be added to a stop words list, like for instance "financial".

2. Aggregate the top words that appear in all the documents and calculate the frecuency of each word among all corpus

The method `Counter` can be useful in case the top words in lists or arrays  
*more about [Counter](https://pymotw.com/2/collections/counter.html) library*

In [27]:
from collections import Counter

In [28]:
# Let's aggregate this list and identify the most common words along 
Counter(words).most_common()[0:10]

[('financial', 87),
 ('value', 73),
 ('assets', 71),
 ('year', 68),
 ('cash', 66),
 ('company', 63),
 ('nthe', 62),
 ('business', 60),
 ('tax', 58),
 ('group', 56)]

In [29]:
counts = [count for word, count in Counter(words).most_common()]

In [30]:
pd.Series(counts).describe()

count    604.000000
mean       4.569536
std       10.909098
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       87.000000
dtype: float64

In [31]:
pd.Series(counts).quantile(.95)

23.40000000000009

In [32]:
pd.Series(counts).hist()

<br>
The creation of stop words lists or expert dictionary is rather flexible, there are not definite rules.  

3. Create a rule on which you consider the financial stop word should be included or not, afterwards add the final list to the `stop_words` object.

Example rule:  
If appears more times than the average word then exclude it from the list

In [33]:
add_stop_words = [word for word, count in Counter(words).most_common() if count > 23]
add_stop_words.remove('risk')

<br>
It is possible to update the predifined stop words list from `sklear` by simply giving the list.  
Example:

In [34]:
# Stop words to add
list_stop_words = ['stopword1', 'stopword2']

In [35]:
from sklearn.feature_extraction import text 

# Add new stop words
new_stop_words = text.ENGLISH_STOP_WORDS.union(list_stop_words)

In [36]:
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

4. Recreate document-term matrix and save the corpus with the NEW list of stop words

Example: `cv = CountVectorizer(stop_words=new_stop_words)`

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words=stop_words)

In [38]:
data_cv = cv.fit_transform(data_clean.report)
data_tokens = cv.get_feature_names()

In [39]:
data_matrix = pd.DataFrame(data_cv.toarray(), columns=data_tokens)
data_matrix.index = data_clean.index

5. Save the following 3 files
    - `AnnualReports_cv.pkl` 
    - `AnnualReports_matrix.pkl` 
    - `AnnualReports_corpus.pkl`

In [40]:
import pickle
pickle.dump(cv, open("pickle/AnnualReports_cv.pkl", "wb"))
pickle.dump(add_stop_words, open("pickle/AnnualReports_stopwords.pkl", "wb"))
data_matrix.to_pickle("pickle/AnnualReports_matrix.pkl")
data_clean.to_pickle("pickle/AnnualReports_corpus.pkl")

In [46]:
file = open('dictionaries/financial_stopwrods.txt', 'w')
file.write('\n'.join(add_stop_words))

215